baseurl: '/ipueblito'
name: i-Pueblito
author: Julian Franco
timezone: America/Bogota

# email: info@enpitalito.com
yotube: https://www.youtube.com/channel/UCiXWpAvZiAxwv7uzBGBagwQ?view_as=subscriber
facebook: https://facebook.com/ipueblito/
instagram: https://instagram.com/ipueblito/
whatsapp: https://wa.me/573115245225
tel: tel://+573115245225

permalink: /:categories/:title/

markdown: kramdown

